### ISSUE TITLE
Update admin.html and home.html

### ISSUE THREAD

**Issue by quaster** [quaster/zpr#7]
#### Change database table

- [x] Delete students FK in Teams Table. 

#### Update htmls

- [x] Join and create buttons should be invisible when user already has a team

- [x] Fix home.html after changing the Teams table.

- [x] Add assigned flag

- [x] Update admin.html so that projects are displayed similarly as in home.html. Do not create JOIN button, but keep the DELETE button (it is already implemented).

**Comment by vic3k515** [comment]
@quaster Should team deletion be implemented? If so, who and when can delete a team.

**Comment by quaster** [comment]
@vic3k515 Students can change teams if they're not assigned permamently to the project. When there is only one student in a team and he leaves the project, then his team should be deleted.

**Comment by vic3k515** [comment]
Now it's working like you said.
