### ISSUE TITLE
Implement enrollment

### ISSUE THREAD

**Issue by quaster** [quaster/zpr#8]
#### Front & back end

- [x] Create button and handle it on server side

#### Enrollment algorithm & implementation

- [x] Create algorithm

- [x]  Implementation

- [x] Tests

- [x] Clean database.cpp

- [x] Clean debug messages

- [x] Make code nicer.

**Comment by quaster** [comment]
#### Useful queries
Select teams with 2 students
```
select count(*) as students_cnt, team_id, project_id from main_site_teams
	inner join login_myuser on 
		team_id=id_team
	group by project_id
	having students_cnt=2;
```

**Comment by quaster** [comment]
1.2 Set assigned to 1 to all projects from query nr 1.1
```
update main_site_projects 
	set assigned=1
	where id_project in 
(select project_id from (
    select count(team_id) as students_cnt, team_id, project_id, assigned from main_site_teams
        inner join login_myuser on 
            team_id=id_team
        inner join main_site_projects on
            project_id=id_project
        group by team_id
        having (students_cnt=2 and assigned=0)
    )
    group by project_id
    having count(project_id)=1);
```

**Comment by quaster** [comment]
#### 2 Enroll teams with 2 students, to projects that have multiple teams (select randomly one of them)
2.1 Select projects' ids (PROJECT_IDS) that have teams with 2 students

2.2 For every project in PROJECT_IDS select teams (TEAMS_IDS) with 2 students

2.3 Choose randomly one of TEAMS_IDS, Assign this team to the project, set Projects.assigned to true. Add to queue (TWO_STUDENTS_QUEUE) every other teams' ids (later assign their team to free project - no team had chosen that project yet)

2.4 Select 1 student teams for this project, add them to ONE_STUDENT_QUEUE.

**Comment by quaster** [comment]
#### 3 Pair two one-student teams that had chosen the same project.

**Comment by quaster** [comment]
#### 4 Assign teams from (ONE_STUDENTS_QUEUE) 

4.1 While there are teams with project_id != null, and == null. Take one of each group. 

4.2 Check if project of the first one is not assigned. 

> If not: 

Create a team of them (name of the first one), update assigned flag=true.

> else:

Reset team_id, add them to ONE_STUDENT_QUEUE.

**Comment by quaster** [comment]
#### 5 Assign teams from (TWO_STUDENTS_QUEUE)

5.1 Select project id (PROJECT_IDS) with flag assigned = 0

5.2 

> For every team in TWO_STUDENTS_QUEUE:

Assign a team to one of PROJECT_IDS, set flag to assigned.

**Comment by quaster** [comment]
@vic3k515 please review the algorithm

**Comment by vic3k515** [comment]
the concept seems ok

**Comment by vic3k515** [comment]
1.3 updated

**Comment by vic3k515** [comment]
2.2 updated

**Comment by quaster** [comment]
3 updated
